SLACK_TOKEN: 'HIDDEN'
SCOPES: ['https://www.googleapis.com/auth/spreadsheets.readonly']

CHANNELS:
  DEFAULT: 'HIDDEN'
  HIVIZ: 'HIDDEN'

AVAILABLE_COMMANDS:
  - HELP
  - METRICS
  - KLIPFOLIO
  - SLA
  - HIDDEN
  - LOGS

RESPONSE:
  METRICS:
    URL: 'HIDDEN'
    RANGE: 'HIDDEN'
  6 STORE:
    URL: 'HIDDEN'
    RANGE: 'HIDDEN'
    OPT_RANGE: 'HIDDEN'
  KLIPFOLIO:
    URL: 'HIDDEN'
    RANGE: 'HIDDEN'
  SLA:
    URL: 'HIDDEN'
    RANGE: 'HIDDEN'
  HELP:
    MESSAGE: "*How to use*:\n
              _FORMAT_: `command` (not case sensitive)\n
              Available commands:\n
              + _Help_ - Instructions on how to use/interact with the bot\n
              + _Metrics_ - Pulls current day ------ [HIDDEN]\n
              + _Klipfolio_ - Pulls last 3 days overview data [HIDDEN]\n
              + _SLA_ - Pulls last 3 days overview data [HIDDEN]\n
              + _HIDDEN_ - Pulls current day --- data, as well as --- data at time of execution for the 6 ---- [HIDDEN]\n
              + _Logs_ - Pulls the up-to-date log file consisting of all successful requests w/ associated data"
  LOGS:
    FILE_PATH: 'HIDDEN'
